### ISSUE TITLE
couldn't locate created empty textfiles

### ISSUE THREAD

**Issue by BarfingLemurs** [adammpkins/llama-terminal-completion#1]
hi, I get this error:

python3 ask_llama.py  -q "hi"
Traceback (most recent call last):
  File "/home/user/llama-terminal-completion/ask_llama.py", line 66, in <module>
    main()
  File "/home/user/llama-terminal-completion/ask_llama.py", line 53, in main
    clear_question_file()
  File "/home/user/llama-terminal-completion/functions.py", line 63, in clear_question_file
    with open(llama_completion_dir + "llama_question.txt", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/llama.cpp/llama_question.txt'

**Comment by adammpkins** [comment]
Is this because you tried clearing the question history without ever having asked a question with python3 ask_llama.py -q "What is PHP?"

**Comment by adammpkins** [comment]
I'm seeing that it seems to think llama-terminal-completion is in /home/user. That doesn't seem right. Is that where it is?

**Comment by adammpkins** [comment]
It's also looking for the llama_question file in the llama.cpp dir. Can I see your environment variables, @BarfingLemurs ?

**Comment by adammpkins** [comment]
@BarfingLemurs If you don't have any further diagnostic issue, I'm going to close this as a user config issue.
