### ISSUE TITLE
.env llama.cpp path incorrect

### ISSUE THREAD

**Issue by JeremyBickel** [adammpkins/llama-terminal-completion#9]
Following the instructions, I set the llama.cpp path, but when I ran the script I got an error: 

llama_init_from_gpt_params: error: failed to load model '/run/media/jeremy/2TB/llama.cpp//run/media/jeremy/2TB/llm_models/solar-10.7b-instruct-v1.0.Q6_K.gguf'

So I had to change the path to:

LLAMA_CPP_DIR="/run/media/jeremy/2TB/llama.cpp/main -m "

I suppose it's alright, but it feels like I missed something. Is this the way you all set it up, too?

**Comment by adammpkins** [comment]
LLAMA_COMPLETION_DIR='/home/adammpkins/Development/llama-terminal-completion/'
LLAMA_CPP_DIR='/home/adammpkins/Development/llama.cpp/'

Is what works for me and what the installer sets. It should work in general. I'm not sure I know how to reproduce this issue. I'm using the mistral instsruct model with it, so I'm not necessarily just using the defaults. @gabrieltsants Any thoughts?

**Comment by JeremyBickel** [comment]
It is a funny error - more a curiosity to me than anything.

.env
# Directory config
LLAMA_COMPLETION_DIR="/run/media/jeremy/2TB/llama-terminal-completion/"
LLAMA_CPP_DIR="/run/media/jeremy/2TB/llama.cpp/"

# LLAMA Questions config
Q_LLAMA_MODEL="/run/media/jeremy/2TB/llm_models/UltraCM-13b.q5_k_m.gguf"
Q_TOKENS=100
Q_TOP_P=0.75
Q_TOP_K=30
Q_CTX=256
Q_R_PENALTY=1.0
Q_OUTPUT=question_output.txt
Q_HISTORY=question_history.txt

# LLAMA Commands config
C_LLAMA_MODEL="/run/media/jeremy/2TB/llm_models/solar-10.7b-instruct-v1.0.Q6_K.gguf"
C_TOKENS=25
C_TOP_P=0.9
C_TOP_K=30
C_CTX=256
C_R_PENALTY=1.0
C_OUTPUT=cmd_output.txt
C_HISTORY=cmd_history.txt

# LLAMA Code config
D_LLAMA_MODEL="/run/media/jeremy/2TB/llm_models/codeninja-1.0-openchat-7b.Q5_K_M.gguf"
D_TOKENS=2000
D_TOP_P=0.05
D_TOP_K=20
D_CTX=256
D_R_PENALTY=0.4
D_OUTPUT=code_output.txt
D_HISTORY=code_history.txt

# Default prompt text - Questions
Q_TEXT_START='The following is a trancript of a conversation with a virtual assistant. The assistant only provides correct answers to questions. \n Assistant: What can I help you with today? \n User: '
Q_TEXT_DELIMITER='Assistant:'
Q_TEXT_END=''

# Default prompt text - Commands
C_TEXT_START='The following command is a single Linux command that will '
C_TEXT_DELIMITER='`'
C_TEXT_END='.: $ `'

ERROR:
llama_init_from_gpt_params: error: failed to load model '/run/media/jeremy/2TB/llama.cpp//run/media/jeremy/2TB/llm_models/solar-10.7b-instruct-v1.0.Q6_K.gguf'

**Comment by gabrieltsants** [comment]
@adammpkins sorry for the delay!

@JeremyBickel Very strange. Considering that bot.py already runs the `main -m` in the [generate_llama_prompt](https://github.com/adammpkins/llama-terminal-completion/blob/main/functions/bot.py) function.

I noticed that you added "**D_**" parameters, you're probably working on the code and made some modifications. Could you validate if the main -p was not accidentally removed in the function `generate_llama_prompt`? [line 41](https://github.com/adammpkins/llama-terminal-completion/blob/ec9a1e32bf307db63b65ee604fdf1fa185904ec4/functions/bot.py#L41C9-L41C18)

**Comment by JeremyBickel** [comment]
@adammpkins 

Yes, it's still there:
        + f"main -m  {(llama_model)} -p '"

The solution is that I was using the full path to the model in the .env file, instead of a relative path from the llama.cpp dir. In fact, the whole prompt generated from the way I had it is:

>python3 ask_llama.py -c 'list files'
>/run/media/jeremy/2TB/llama.cpp/main -m main -m  /run/media/jeremy/2TB/llama.cpp/main -m /run/media/jeremy/2TB/llm_models/solar-10.7b-instruct-v1.0.Q6_K.gguf -p 'The following command is a single Linux command that will list files.: $ `' -n 25 -e --top-p 0.9 --top-k 30 --ctx-size 256 --repeat-penalty 1.0  --log-disable

Evidently, those redundant 'main -m' parts didn't hinder it, so it would run like that.

So, I took out the 'main -m ' part from LLAMA_CPP_DIR and I changed the model paths to be relative to that directory.
